services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productdb

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  product-service:
    image: product-service:1.0
    container_name: product-service-container

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data: